# Copyright 2024 Khalil Estell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Platform 📦 Package 🚀 Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      library:
        type: string
        default: ${{ github.event.repository.name }}
      repo:
        type: string
        default: ${{ github.repository }}
      conan_version:
        type: string
        default: "2.0.14"
      profile:
        type: string
        required: true
      upload:
        type: boolean
        default: false
      processor_profile:
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          repository: ${{ inputs.repo }}

      - name: 📥 Install CMake 3.27.7
        run: pip3 install cmake==3.27.7

      - name: 📥 Install Conan ${{ inputs.conan_version }}
        run: pip3 install conan==${{ inputs.conan_version }}

      - name: 📡 Add `libhal` repo to conan remotes
        run: conan remote add libhal
          https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: 📡 Create and setup default profile
        run: conan profile detect --force

      - name: 👁️‍🗨️ Show conan profile
        run: conan profile show

      - name: 📡 Sign into JFrog Artifactory
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          API_KEY: ${{ secrets.JFROG_LIBHAL_TRUNK_API_KEY }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_USER }}
        run: conan remote login -p $API_KEY libhal $JFROG_USER

      - name: Install libhal settings_user.yml
        run: conan config install -sf profiles/baremetal https://github.com/libhal/conan-config.git

      - name: Install host OS profiles
        run: conan config install -sf profiles/x86_64/linux/ -tf profiles https://github.com/libhal/conan-config.git

      - name: Install processor profiles
        if: inputs.processor_profile != ''
        run: conan config install -tf profiles -sf conan/profiles/ ${{ inputs.processor_profile }}

      - name: Install platform profiles
        run: conan config install -tf profiles conan/profiles/

      - name: 📦 Create `Debug` package for ${{ inputs.profile }}
        run: conan create . -pr ${{ inputs.profile }} -s build_type=Debug -b missing

      - name: 📦 Create `RelWithDebInfo` package for ${{ inputs.profile }}
        run: conan create . -pr ${{ inputs.profile }} -s build_type=RelWithDebInfo -b missing

      - name: 📦 Create `MinSizeRel` package for ${{ inputs.profile }}
        run: conan create . -pr ${{ inputs.profile }} -s build_type=MinSizeRel -b missing

      - name: 📦 Create `Release` package for ${{ inputs.profile }}
        run: conan create . -pr ${{ inputs.profile }} -s build_type=Release -b missing

      - name: Check if `demos/` directory existence
        id: check_demos_dir
        uses: andstor/file-existence-action@v1
        with:
          files: "demos/"

      - name: 🏗️ Build demos for ${{ inputs.profile }}
        if: steps.check_demos_dir.outputs.files_exists == 'true'
        run: conan build demos -pr ${{ inputs.profile }} -s build_type=MinSizeRel

      - name: 🆙 Upload package to `libhal` repo
        if: startsWith(github.ref, 'refs/tags/') && inputs.upload
        run: conan upload "${{ inputs.library }}/${{ github.ref_name }}" --confirm -r=libhal
